language: java
jdk:
- openjdk8

addons:
  sonarcloud:
    organization: "falessiinguniroma2it"
    token:
      secure: "726937ad8e610377beb7cb635199b5045cba1bd2"
script:
- ant build
- sonar-scanner